--c99 -c --cpu Cortex-M4.fp.sp -D__MICROLIB -g -O0 --apcs=interwork 
--split_sections -I ../emva_source/framework/kfifo -I 
../emva_source/framework/list -I 
../emva_source/framework/malloc -I 
../emva_source/framework/serial -I 
../emva_source/framework/time -I 
../emva_source/framework -I 
../emva_source/driver/serial -I 
../emva_source/driver/time -I 
../emva_source/driver/util/error -I 
../emva_source/driver/template/dev_init -I 
../emva_source/hal/inc -I ../emva_source/bsp -I 
../emva_source/driver/template/character_dev -I 
../emva_source/driver/util/malloc -I 
../emva_source/driver/util/list -I 
../emva_source/driver/kfifo -I 
../emva_source/framework/mem_pool -I 
../emva_source/driver/util/mem_pool -I 
../emva_source -I ../emva_source/framework/os -D__UVISION_VERSION="530" -DSTM32F411xE -D_RTE_
-o .\Objects\*.o --omf_browse .\Objects\*.crf --depend .\Objects\*.d


save indoor copy song sniff boring shell shop grit song fiber update